files:
  - source: /org/docs/**/*.ini
    translation: /translationsщкп/%language%/%original_file_name%
targets:
  - name: ios strings
    sources:
      - /*json
    file: /tr/bun/%language%/example.strings
    format: macosx
