preserve_hierarchy: true
files:
  - source: /*mdx
    translation: /translations/%two_letters_code%/**/%original_file_name%
    dest: /**/%original_file_name%
    content_segmentation: 0
    skip_untranslated_files: true
