export_languages:
  - fr
files:
  - first_line_contains_header: true
    multilingual_spreadsheet: true
    scheme: 'identifier,context,source_phrase,es-ES,fr'
    source: /*.csv
    translation: /translationfiles/%two_letters_code%_%original_file_name%
    translation_replace:
      fr_: ''
